#include "cmplrs/ucode.h"

type
    thing = packed record 
    fill: packed array[0..2] of char;
    op: Uopcode;
    pos: integer;
end;

var 
Utab: array[first(Uopcode)..last(Uopcode)] of Utabrec;


procedure Uini;
var
    pos: integer;
    op: Uopcode;

    
    procedure add_record(opcode: Uopcode; Opcname: Opcstring); internal;
    begin
        Utab[opcode].Opcname := Opcname; \
        op := opcode; \
        pos := 0; \
    end;
    
    procedure add_operand(operand: Uoperand); internal;
    begin
        pos := pos + 1;
        Utab[op].Format[pos] := operand;
    end;
begin
    add_record(Uabs,  "ABS "); add_operand(Sdtype); add_operand(Send);
    add_record(Uadd,  "ADD "); add_operand(Sdtype); add_operand(Send);
    add_record(Uadj,  "ADJ "); add_operand(Sdtype); add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Ualia, "ALIA"); add_operand(Ssomenumber); add_operand(Slexlev); add_operand(Send);    
    add_record(Uand,  "AND "); add_operand(Sdtype); add_operand(Send);
    add_record(Uaos,  "AOS "); add_operand(Send);
    add_record(Ubgn,  "BGN "); add_operand(Sblockno); add_operand(Slength); add_operand(Soffset); add_operand(Send);
    add_record(Ubgnb, "BGNB"); add_operand(Sblockno); add_operand(Send);
    add_record(Ubsub, "BSUB"); add_operand(Sdtype); add_operand(Send);
    add_record(Uchkt, "CHKT"); add_operand(Send);
    add_record(Uchkh, "CHKH"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Uchkl, "CHKL"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Uchkn, "CHKN"); add_operand(Send);
    add_record(Ucia,  "CIA "); add_operand(Sdtype); add_operand(Slength); add_operand(Slexlev); add_operand(Soffset); add_operand(Ssomenumber); add_operand(Sconstval); add_operand(Send);
    add_record(Uclab, "CLAB"); add_operand(Slabel0); add_operand(Slength); add_operand(Send);
    add_record(Uclbd, "CLBD"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Ucubd, "CUBD"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Uctrl, "CTRL"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno);  add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Ucomm, "COMM"); add_operand(Scomment); add_operand(Send);
    add_record(Ucup,  "CUP "); add_operand(Sdtype); add_operand(Slexlev); add_operand(Sblockno); add_operand(Spop); add_operand(Spush); add_operand(Sexternal); add_operand(Send);
    add_record(Ucvt,  "CVT "); add_operand(Sdtype); add_operand(Sdtype2); add_operand(Send);
    add_record(Ucvtl, "CVTL"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Udec,  "DEC "); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Udef,  "DEF "); add_operand(Smtype); add_operand(Slength); add_operand(Send);
    add_record(Udif,  "DIF "); add_operand(Sdtype); add_operand(Slength); add_operand(Send);
    add_record(Udiv,  "DIV "); add_operand(Sdtype); add_operand(Send);
    add_record(Udup,  "DUP "); add_operand(Sdtype); add_operand(Send);
    add_record(Uend,  "END "); add_operand(Sblockno); add_operand(Send);
    add_record(Uendb, "ENDB"); add_operand(Sblockno); add_operand(Send);
    add_record(Uent,  "ENT "); add_operand(Sdtype); add_operand(Slexlev); add_operand(Sblockno); add_operand(Spop); add_operand(Spush); add_operand(Sexternal); add_operand(Send);
    add_record(Uaent, "AENT"); add_operand(Sdtype); add_operand(Slexlev); add_operand(Sblockno); add_operand(Spop); add_operand(Spush); add_operand(Sexternal); add_operand(Send);
    add_record(Uequ,  "EQU "); add_operand(Sdtype); add_operand(Send);
    add_record(Ufjp,  "FJP "); add_operand(Slabel1); add_operand(Slexlev); add_operand(Send);
    add_record(Ugeq,  "GEQ "); add_operand(Sdtype); add_operand(Send);
    add_record(Ugrt,  "GRT "); add_operand(Sdtype); add_operand(Send);
    add_record(Ufill, "FILL"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Uidx,  "IDX "); add_operand(Sdtype); add_operand(Send);
    add_record(Uiequ, "IEQU"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Uigeq, "IGEQ"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Uigrt, "IGRT"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Uileq, "ILEQ"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Uiles, "ILES"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Uilod, "ILOD"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slexlev); add_operand(Slength); add_operand(Soffset); add_operand(Send);
    add_record(Uineq, "INEQ"); add_operand(Sdtype); add_operand(Slength); add_operand(Send);
    add_record(Uinc,  "INC "); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Uinit, "INIT"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Soffset2); add_operand(Slength); add_operand(SarrayOffset); add_operand(Slexlev); add_operand(Sinitval); add_operand(Send);
    add_record(Uinn,  "INN "); add_operand(Sdtype); add_operand(Slength); add_operand(Ssomenumber); add_operand(Send);
    add_record(Uint,  "INT "); add_operand(Sdtype); add_operand(Slength); add_operand(Send);
    add_record(Uior,  "IOR "); add_operand(Sdtype); add_operand(Send);
    add_record(Uistr, "ISTR"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Slexlev); add_operand(Slength); add_operand(Soffset); add_operand(Send);
    add_record(Uixa,  "IXA "); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Ulab,  "LAB "); add_operand(Slabel0); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Uldef, "LDEF"); add_operand(Slabel0); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Ulbd,  "LBD "); add_operand(Send);
    add_record(Ulca,  "LCA "); add_operand(Sdtype); add_operand(Slength); add_operand(Ssomenumber); add_operand(Sconstval); add_operand(Send);
    add_record(Uilda, "ILDA"); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Soffset2); add_operand(Send);
    add_record(Ulda,  "LDA "); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Soffset2); add_operand(Send);
    add_record(Uldc,  "LDC "); add_operand(Sdtype); add_operand(Slength); add_operand(Sconstval); add_operand(Send);
    add_record(Uldsp, "LDSP"); add_operand(Send);
    add_record(Uldap, "LDAP"); add_operand(Send);
    add_record(Uleq,  "LEQ "); add_operand(Sdtype); add_operand(Send);
    add_record(Ules,  "LES "); add_operand(Sdtype); add_operand(Send);
    add_record(Ulex,  "LEX "); add_operand(Slexlev); add_operand(Sblockno); add_operand(Send);
    add_record(Uloc,  "LOC "); add_operand(Slexlev); add_operand(Ssomenumber); add_operand(Send);
    add_record(Ulod,  "LAD "); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Umin,  "MIN "); add_operand(Sdtype); add_operand(Send);
    add_record(Umax,  "MAX "); add_operand(Sdtype); add_operand(Send);
    add_record(Umod,  "MOD "); add_operand(Sdtype); add_operand(Send);
    add_record(Urem,  "REM "); add_operand(Sdtype); add_operand(Send);
    add_record(Umov,  "MOV "); add_operand(Sdtype); add_operand(Slexlev); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Umpy,  "MPY "); add_operand(Sdtype); add_operand(Send);
    add_record(Umst,  "MST "); add_operand(Slexlev); add_operand(Send);
    add_record(Umtag, "MTAG"); add_operand(Ssomenumber); add_operand(Slexlev); add_operand(Send);
    add_record(Umus,  "MUS "); add_operand(Sdtype); add_operand(Slength); add_operand(Send);
    add_record(Uneg,  "NEG "); add_operand(Sdtype); add_operand(Send);
    add_record(Uneq,  "NEQ "); add_operand(Sdtype); add_operand(Send);
    add_record(Unop,  "NOP "); add_operand(Send);
    add_record(Unot,  "NOT "); add_operand(Sdtype); add_operand(Send);
    add_record(Uodd,  "ODD "); add_operand(Sdtype); add_operand(Send);
    add_record(Uxpar, "XPAR"); add_operand(Sdtype); add_operand(Send);
    add_record(Uoptn, "OPTN"); add_operand(Ssomenumber); add_operand(Slength); add_operand(Send);
    add_record(Upar,  "PAR "); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Updef, "PDEF"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Upop,  "POP "); add_operand(Sdtype); add_operand(Send);
    add_record(Uregs, "REGS"); add_operand(Slexlev); add_operand(Ssomenumber); add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Uret,  "RET "); add_operand(Send);
    add_record(Urlda, "RLDA"); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Urldc, "RLDC"); add_operand(Sdtype); add_operand(Slength); add_operand(Ssomenumber); add_operand(Sconstval); add_operand(Send);
    add_record(Urlod, "RLOD"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Urnd,  "RND "); add_operand(Sdtype); add_operand(Sdtype2); add_operand(Send);
    add_record(Urpar, "RPAR"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Urstr, "RSTR"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Usdef, "SDEF"); add_operand(Sblockno); add_operand(Slength); add_operand(Send);
    add_record(Uasym, "ASYM"); add_operand(Sblockno); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Uhsym, "HSYM"); add_operand(Sblockno); add_operand(Slength); add_operand(Send);
    add_record(Usgs,  "SGS "); add_operand(Sdtype); add_operand(Slength); add_operand(Send);
    add_record(Usqr,  "SQR "); add_operand(Sdtype); add_operand(Send);
    add_record(Usqrt, "SQRT"); add_operand(Sdtype); add_operand(Send);
    add_record(Ustep, "STEP"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Ustp,  "STP "); add_operand(Sblockno); add_operand(Send);
    add_record(Ustr,  "STR "); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Send);
    add_record(Ustsp, "STSP"); add_operand(Send);
    add_record(Usub,  "SUB "); add_operand(Sdtype); add_operand(Send);
    add_record(Uswp,  "SWP "); add_operand(Sdtype); add_operand(Sdtype2); add_operand(Send);
    add_record(Utjp,  "TJP "); add_operand(Slabel1); add_operand(Slexlev); add_operand(Send);
    add_record(Utyp,  "TYP "); add_operand(Sdtype); add_operand(Sdtype2); add_operand(Send);
    add_record(Uujp,  "UJP "); add_operand(Slabel1); add_operand(Send);
    add_record(Uuni,  "UNI "); add_operand(Sdtype); add_operand(Slength); add_operand(Send);
    add_record(Uxjp,  "XJP "); add_operand(Sdtype); add_operand(Slabel1); add_operand(Slabel2); add_operand(Slbound); add_operand(Shbound); add_operand(Send);
    add_record(Uxor,  "XOR "); add_operand(Sdtype); add_operand(Send);
    add_record(Ucsym, "CSYM"); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Uesym, "ESYM"); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Ufsym, "FSYM"); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Ugsym, "GSYM"); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Ulsym, "LSYM"); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Ushl,  "SHL "); add_operand(Sdtype); add_operand(Send);
    add_record(Ushr,  "SHR "); add_operand(Sdtype); add_operand(Send);
    add_record(Ulnot, "LNOT"); add_operand(Sdtype); add_operand(Send);
    add_record(Uicuf, "ICUF"); add_operand(Sdtype); add_operand(Spop); add_operand(Spush); add_operand(Sexternal); add_operand(Send);
    add_record(Uisld, "ISLD"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Uisst, "ISST"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Upmov, "PMOV"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Umpmv, "MPMV"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Uunal, "UNAL"); add_operand(Slexlev); add_operand(Ssomenumber); add_operand(Sdtypenum); add_operand(Send);
    add_record(Uvreg, "VREG"); add_operand(Sdtype); add_operand(Smtype); add_operand(Sblockno); add_operand(Soffset); add_operand(Slength); add_operand(Slexlev); add_operand(Send);
    add_record(Uijp,  "IJP "); add_operand(Send);
    add_record(Ucg1,  "CG1 "); add_operand(Send);
    add_record(Ucg2,  "CG2 "); add_operand(Send);
    add_record(Utpeq, "TPEQ"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Utpne, "TPNE"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Utplt, "TPLT"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Utpgt, "TPGT"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Utpge, "TPGE"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Utple, "TPLE"); add_operand(Sdtype); add_operand(Ssomenumber); add_operand(Send);
    add_record(Uubd,  "UDB "); add_operand(Send);
    add_record(Ulbgn, "LBGN"); add_operand(Ssomenumber); add_operand(Send);
    add_record(Ulbdy, "LBDY"); add_operand(Slexlev); add_operand(Send);
    add_record(Ultrm, "LTRM"); add_operand(Send);
    add_record(Ulend, "LEND"); add_operand(Send);
    add_record(Ussym, "SSYM"); add_operand(Sdtype); add_operand(Sblockno); add_operand(Slexlev); add_operand(Sconstval); add_operand(Send);
    add_record(Usign, "SIGN"); add_operand(Sdtype); add_operand(Send);
    add_record(Uildi, "ILDI"); add_operand(Sdtype); add_operand(Slexlev); add_operand(Slength); add_operand(Soffset); add_operand(Send);
    add_record(Uisti, "ISTI"); add_operand(Sdtype); add_operand(Slexlev); add_operand(Slength); add_operand(Soffset); add_operand(Send);
    add_record(Uirld, "IRLD"); add_operand(Sdtype); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Uirst, "IRST"); add_operand(Sdtype); add_operand(Sblockno); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Uldrc, "LDRC"); add_operand(Sdtype); add_operand(Slength); add_operand(Sblockno); add_operand(Send);
    add_record(Urcuf, "RCUF"); add_operand(Sdtype); add_operand(Sblockno); add_operand(Spop); add_operand(Spush); add_operand(Sexternal); add_operand(Send);
    add_record(Umsym, "MSYM"); add_operand(Sblockno); add_operand(Soffset); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Uksym, "KSYM"); add_operand(Sblockno); add_operand(Soffset); add_operand(Slexlev); add_operand(Slength); add_operand(Send);
    add_record(Uosym, "OSYM"); add_operand(Sblockno); add_operand(Soffset); add_operand(Send);



    for op := first(Uopcode) to last(Uopcode) do begin
        Utab[op].Hasattr := false;
        Utab[op].Hasconst := false;
        Utab[op].Instlength := 2;
        Utab[op].Stack_pop := 0;
        Utab[op].Stack_push := 0;
    end;

    Utab[Ulod].Hasattr := true;
    Utab[Ustr].Hasattr := true;
    Utab[Uilod].Hasattr := true;
    Utab[Uistr].Hasattr := true;
    Utab[Uildi].Hasattr := true;
    Utab[Uisti].Hasattr := true;
    Utab[Uirld].Hasattr := true;
    Utab[Uirst].Hasattr := true;
    Utab[Umov].Hasattr := true;
    Utab[Uabs].Hasattr := true;
    Utab[Uneg].Hasattr := true;
    Utab[Usqr].Hasattr := true;
    Utab[Uchkn].Hasattr := true;
    Utab[Uchkt].Hasattr := true;
    Utab[Ulnot].Hasattr := true;
    Utab[Unot].Hasattr := true;
    Utab[Uodd].Hasattr := true;
    Utab[Usqrt].Hasattr := true;
    Utab[Ucvtl].Hasattr := true;
    Utab[Udec].Hasattr := true;
    Utab[Uinc].Hasattr := true;
    Utab[Uchkh].Hasattr := true;
    Utab[Uchkl].Hasattr := true;
    Utab[Usgs].Hasattr := true;
    Utab[Ucvt].Hasattr := true;
    Utab[Urnd].Hasattr := true;
    Utab[Uadj].Hasattr := true;
    Utab[Uadd].Hasattr := true;
    Utab[Udiv].Hasattr := true;
    Utab[Umod].Hasattr := true;
    Utab[Umpy].Hasattr := true;
    Utab[Usub].Hasattr := true;
    Utab[Urem].Hasattr := true;
    Utab[Uand].Hasattr := true;
    Utab[Uequ].Hasattr := true;
    Utab[Ugeq].Hasattr := true;
    Utab[Ugrt].Hasattr := true;
    Utab[Uior].Hasattr := true;
    Utab[Uleq].Hasattr := true;
    Utab[Ules].Hasattr := true;
    Utab[Umax].Hasattr := true;
    Utab[Umin].Hasattr := true;
    Utab[Uneq].Hasattr := true;
    Utab[Ushl].Hasattr := true;
    Utab[Ushr].Hasattr := true;
    Utab[Uxor].Hasattr := true;
    Utab[Uixa].Hasattr := true;
    Utab[Uint].Hasattr := true;
    Utab[Udif].Hasattr := true;
    Utab[Umus].Hasattr := true;
    Utab[Uuni].Hasattr := true;
    Utab[Uinn].Hasattr := true;
    Utab[Uiequ].Hasattr := true;
    Utab[Uigrt].Hasattr := true;
    Utab[Uigeq].Hasattr := true;
    Utab[Uileq].Hasattr := true;
    Utab[Uiles].Hasattr := true;
    Utab[Uineq].Hasattr := true;
    Utab[Usign].Hasattr := true;
    Utab[Uisld].Hasattr := true;
    Utab[Uisst].Hasattr := true;

    Utab[Ucia].Hasconst := true;
    Utab[Ucomm].Hasconst := true;
    Utab[Uinit].Hasconst := true;
    Utab[Ulca].Hasconst := true;
    Utab[Uldc].Hasconst := true;
    Utab[Urldc].Hasconst := true;
    Utab[Ussym].Hasconst := true;

    Utab[Uadj].Instlength := 4;
    Utab[Ubgn].Instlength := 4;
    Utab[Ubgnb].Instlength := 2;
    Utab[Uchkh].Instlength := 2;
    Utab[Uchkl].Instlength := 2;
    Utab[Ucia].Instlength := 4;
    Utab[Uclab].Instlength := 4;
    Utab[Uclbd].Instlength := 2;
    Utab[Ucubd].Instlength := 2;
    Utab[Uctrl].Instlength := 4;
    Utab[Ucomm].Instlength := 4;
    Utab[Ucup].Instlength := 4;
    Utab[Ucvt].Instlength := 4;
    Utab[Ucvtl].Instlength := 2;
    Utab[Udec].Instlength := 2;
    Utab[Uinc].Instlength := 2;
    Utab[Udef].Instlength := 4;
    Utab[Udif].Instlength := 4;
    Utab[Uint].Instlength := 4;
    Utab[Uuni].Instlength := 4;
    Utab[Uend].Instlength := 2;
    Utab[Uendb].Instlength := 2;
    Utab[Uent].Instlength := 4;
    Utab[Uaent].Instlength := 4;
    Utab[Uiequ].Instlength := 4;
    Utab[Uigeq].Instlength := 4;
    Utab[Uigrt].Instlength := 4;
    Utab[Uileq].Instlength := 4;
    Utab[Uiles].Instlength := 4;
    Utab[Uineq].Instlength := 4;
    Utab[Ufjp].Instlength := 2;
    Utab[Utjp].Instlength := 2;
    Utab[Uujp].Instlength := 2;
    Utab[Ufill].Instlength := 4;
    Utab[Uildv].Instlength := 4;
    Utab[Uilod].Instlength := 4;
    Utab[Uinit].Instlength := 6;
    Utab[Uinn].Instlength := 4;
    Utab[Uistv].Instlength := 4;
    Utab[Uistr].Instlength := 4;
    Utab[Uixa].Instlength := 2;
    Utab[Ulab].Instlength := 4;
    Utab[Uldef].Instlength := 4;
    Utab[Ulca].Instlength := 4;
    Utab[Uilda].Instlength := 6;
    Utab[Ulbgn].Instlength := 2;
    Utab[Ulda].Instlength := 6;
    Utab[Uldc].Instlength := 4;
    Utab[Ulex].Instlength := 2;
    Utab[Uloc].Instlength := 2;
    Utab[Ulod].Instlength := 4;
    Utab[Umov].Instlength := 4;
    Utab[Umus].Instlength := 4;
    Utab[Uoptn].Instlength := 4;
    Utab[Upar].Instlength := 4;
    Utab[Updef].Instlength := 4;
    Utab[Uregs].Instlength := 4;
    Utab[Urlda].Instlength := 4;
    Utab[Urldc].Instlength := 4;
    Utab[Urlod].Instlength := 4;
    Utab[Urnd].Instlength := 4;
    Utab[Urpar].Instlength := 4;
    Utab[Urstr].Instlength := 4;
    Utab[Usdef].Instlength := 4;
    Utab[Uasym].Instlength := 4;
    Utab[Uhsym].Instlength := 4;
    Utab[Usgs].Instlength := 4;
    Utab[Ustep].Instlength := 2;
    Utab[Ustp].Instlength := 2;
    Utab[Ustr].Instlength := 4;
    Utab[Uswp].Instlength := 4;
    Utab[Uxjp].Instlength := 8;
    Utab[Ucsym].Instlength := 4;
    Utab[Uesym].Instlength := 4;
    Utab[Ufsym].Instlength := 4;
    Utab[Ugsym].Instlength := 4;
    Utab[Ulsym].Instlength := 4;
    Utab[Uicuf].Instlength := 4;
    Utab[Uisld].Instlength := 4;
    Utab[Uisst].Instlength := 4;
    Utab[Upmov].Instlength := 4;
    Utab[Umpmv].Instlength := 4;
    Utab[Uunal].Instlength := 2;
    Utab[Uvreg].Instlength := 4;
    Utab[Utpeq].Instlength := 2;
    Utab[Utpne].Instlength := 2;
    Utab[Utplt].Instlength := 2;
    Utab[Utpgt].Instlength := 2;
    Utab[Utpge].Instlength := 2;
    Utab[Utple].Instlength := 2;
    Utab[Utyp].Instlength := 4;
    Utab[Ussym].Instlength := 4;
    Utab[Urcuf].Instlength := 4;
    Utab[Uldrc].Instlength := 4;
    Utab[Umsym].Instlength := 4;
    Utab[Uksym].Instlength := 4;
    Utab[Uosym].Instlength := 4;
    Utab[Uildi].Instlength := 4;
    Utab[Uisti].Instlength := 4;
    Utab[Uirld].Instlength := 4;
    Utab[Uirst].Instlength := 4;

    Utab[Ustr].Stack_pop := 1;
    Utab[Uchkn].Stack_pop := 1;
    Utab[Uchkt].Stack_pop := 1;
    Utab[Uabs].Stack_pop := 1;
    Utab[Ubsub].Stack_pop := 2;
    Utab[Uneg].Stack_pop := 1;
    Utab[Usqr].Stack_pop := 1;
    Utab[Ulnot].Stack_pop := 1;
    Utab[Unot].Stack_pop := 1;
    Utab[Uodd].Stack_pop := 1;
    Utab[Usqrt].Stack_pop := 1;
    Utab[Ucvtl].Stack_pop := 1;
    Utab[Udec].Stack_pop := 1;
    Utab[Uinc].Stack_pop := 1;
    Utab[Uchkh].Stack_pop := 1;
    Utab[Uchkl].Stack_pop := 1;
    Utab[Usgs].Stack_pop := 1;
    Utab[Ucvt].Stack_pop := 1;
    Utab[Utyp].Stack_pop := 1;
    Utab[Urnd].Stack_pop := 1;
    Utab[Uadj].Stack_pop := 1;
    Utab[Uilda].Stack_pop := 1;
    Utab[Ulbd].Stack_pop := 1;
    Utab[Uubd].Stack_pop := 1;
    Utab[Uadd].Stack_pop := 2;
    Utab[Udiv].Stack_pop := 2;
    Utab[Umod].Stack_pop := 2;
    Utab[Umpy].Stack_pop := 2;
    Utab[Usub].Stack_pop := 2;
    Utab[Urem].Stack_pop := 2;
    Utab[Uand].Stack_pop := 2;
    Utab[Uequ].Stack_pop := 2;
    Utab[Ugeq].Stack_pop := 2;
    Utab[Ugrt].Stack_pop := 2;
    Utab[Uior].Stack_pop := 2;
    Utab[Uleq].Stack_pop := 2;
    Utab[Ules].Stack_pop := 2;
    Utab[Umax].Stack_pop := 2;
    Utab[Umin].Stack_pop := 2;
    Utab[Uneq].Stack_pop := 2;
    Utab[Ushl].Stack_pop := 2;
    Utab[Ushr].Stack_pop := 2;
    Utab[Uxor].Stack_pop := 2;
    Utab[Uixa].Stack_pop := 2;
    Utab[Uidx].Stack_pop := 3;
    Utab[Uint].Stack_pop := 2;
    Utab[Udif].Stack_pop := 2;
    Utab[Umus].Stack_pop := 2;
    Utab[Uuni].Stack_pop := 2;
    Utab[Uinn].Stack_pop := 2;
    Utab[Uilod].Stack_pop := 1;
    Utab[Uistr].Stack_pop := 2;
    Utab[Uildi].Stack_pop := 2;
    Utab[Uisti].Stack_pop := 3;
    Utab[Uirld].Stack_pop := 1;
    Utab[Uirst].Stack_pop := 2;
    Utab[Uisld].Stack_pop := 1;
    Utab[Uisst].Stack_pop := 2;
    Utab[Umov].Stack_pop := 2;
    Utab[Ufill].Stack_pop := 2;
    Utab[Uiequ].Stack_pop := 2;
    Utab[Uigeq].Stack_pop := 2;
    Utab[Uigrt].Stack_pop := 2;
    Utab[Uileq].Stack_pop := 2;
    Utab[Uiles].Stack_pop := 2;
    Utab[Uineq].Stack_pop := 2;
    Utab[Ufjp].Stack_pop := 1;
    Utab[Utjp].Stack_pop := 1;
    Utab[Uijp].Stack_pop := 1;
    Utab[Uxjp].Stack_pop := 1;
    Utab[Uicuf].Stack_pop := 1;
    Utab[Upar].Stack_pop := 1;
    Utab[Uxpar].Stack_pop := 1;
    Utab[Upmov].Stack_pop := 1;
    Utab[Umpmv].Stack_pop := 1;
    Utab[Utpeq].Stack_pop := 2;
    Utab[Utpge].Stack_pop := 2;
    Utab[Utpgt].Stack_pop := 2;
    Utab[Utple].Stack_pop := 2;
    Utab[Utplt].Stack_pop := 2;
    Utab[Utpne].Stack_pop := 2;
    Utab[Upop].Stack_pop := 1;
    Utab[Uswp].Stack_pop := 1;
    Utab[Uaos].Stack_pop := 1;
    Utab[Ustsp].Stack_pop := 1;
    Utab[Usign].Stack_pop := 2;

    Utab[Ulod].Stack_push := 1;
    Utab[Uldc].Stack_push := 1;
    Utab[Uldrc].Stack_push := 1;
    Utab[Ulca].Stack_push := 1;
    Utab[Ulda].Stack_push := 1;
    Utab[Uchkn].Stack_push := 1;
    Utab[Uabs].Stack_push := 1;
    Utab[Ubsub].Stack_push := 1;
    Utab[Uneg].Stack_push := 1;
    Utab[Usqr].Stack_push := 1;
    Utab[Ulnot].Stack_push := 1;
    Utab[Unot].Stack_push := 1;
    Utab[Uodd].Stack_push := 1;
    Utab[Usqrt].Stack_push := 1;
    Utab[Ucvtl].Stack_push := 1;
    Utab[Udec].Stack_push := 1;
    Utab[Uinc].Stack_push := 1;
    Utab[Uchkh].Stack_push := 1;
    Utab[Uchkl].Stack_push := 1;
    Utab[Usgs].Stack_push := 1;
    Utab[Ucvt].Stack_push := 1;
    Utab[Utyp].Stack_push := 1;
    Utab[Urnd].Stack_push := 1;
    Utab[Uadj].Stack_push := 1;
    Utab[Uilda].Stack_push := 1;
    Utab[Ulbd].Stack_push := 1;
    Utab[Uubd].Stack_push := 1;
    Utab[Uadd].Stack_push := 1;
    Utab[Udiv].Stack_push := 1;
    Utab[Umod].Stack_push := 1;
    Utab[Umpy].Stack_push := 1;
    Utab[Usub].Stack_push := 1;
    Utab[Urem].Stack_push := 1;
    Utab[Uand].Stack_push := 1;
    Utab[Uequ].Stack_push := 1;
    Utab[Ugeq].Stack_push := 1;
    Utab[Ugrt].Stack_push := 1;
    Utab[Uior].Stack_push := 1;
    Utab[Uleq].Stack_push := 1;
    Utab[Ules].Stack_push := 1;
    Utab[Umax].Stack_push := 1;
    Utab[Umin].Stack_push := 1;
    Utab[Uneq].Stack_push := 1;
    Utab[Ushl].Stack_push := 1;
    Utab[Ushr].Stack_push := 1;
    Utab[Uxor].Stack_push := 1;
    Utab[Uixa].Stack_push := 1;
    Utab[Uidx].Stack_push := 1;
    Utab[Uint].Stack_push := 1;
    Utab[Udif].Stack_push := 1;
    Utab[Umus].Stack_push := 1;
    Utab[Uuni].Stack_push := 1;
    Utab[Uinn].Stack_push := 1;
    Utab[Uilod].Stack_push := 1;
    Utab[Uildi].Stack_push := 1;
    Utab[Uirld].Stack_push := 1;
    Utab[Uisld].Stack_push := 1;
    Utab[Uiequ].Stack_push := 1;
    Utab[Uigeq].Stack_push := 1;
    Utab[Uigrt].Stack_push := 1;
    Utab[Uileq].Stack_push := 1;
    Utab[Uiles].Stack_push := 1;
    Utab[Uineq].Stack_push := 1;
    Utab[Udup].Stack_push := 1;
    Utab[Uswp].Stack_push := 1;
    Utab[Uldsp].Stack_push := 1;
    Utab[Uldap].Stack_push := 1;
    Utab[Usign].Stack_push := 1;

end;

procedure getutabrec(
	    Uopc     : Uopcode;
	var Utabr    : Utabrec);
begin
    Utabr := Utab[Uopc];
end;
