#ifndef EMIT_H
#define EMIT_H
procedure save_i_ptrs(); external;
procedure restore_i_ptrs(); external;
procedure init_ibuffer(); external;
procedure grow_ibuffer(); external;
function create_local_label(labelno: cardinal): integer; external;
procedure emit_vers(); external;
procedure emit_rob(op: asmcodes; reg1: registers; immediate: integer; reg2: registers; mem_tag: integer); external;
procedure emit_rab(op: asmcodes; reg1: registers; immediate: integer; symno: integer; reg2: registers; mem_tag: integer); external;
procedure emit_rrab(op: asmcodes; reg1: registers; immediate: integer; symno: integer; reg2: registers); external;
procedure emit_rllb(op: asmcodes; reg1: registers; immediate: integer; labelno: cardinal; reg2: registers); external;
procedure emit_ra(op: asmcodes; reg1: registers; symno: integer; immediate: integer; mem_tag: integer); external;
procedure emit_ri_(op: asmcodes; reg1: registers; immediate: integer; formextn: format_extn); external;
procedure emit_rii(op: asmcodes; reg1: registers; value: Valu); external;
procedure emit_rfi(op: asmcodes; reg1: registers; var value: Valu); external;
procedure emit_rrfi(op: asmcodes; reg1: registers; symno: cardinal); external;
procedure emit_rrr(op: asmcodes; reg1: registers; reg2: registers; reg3: registers); external;
procedure emit_rri_(op: asmcodes; reg1: registers; reg2: registers; immediate: integer; formextn: format_extn); external;
procedure emit_rrri(op: asmcodes; reg1: registers; reg2: registers; symno: cardinal); external;
procedure emit_rr(op: asmcodes; reg1: registers; reg2: registers); external;
procedure emit_a(op: asmcodes; symno: cardinal; immediate: integer; formextn : format_extn); external;
procedure emit_r(op: asmcodes; reg1: registers); external;
procedure emit_i(op: asmcodes; immediate: integer); external;
procedure emit_rrl(op: asmcodes; reg1: registers; reg2: registers; symno: cardinal); external;
procedure emit_rrll(op: asmcodes; reg1: registers; reg2: registers; labelno: cardinal); external;
procedure emit_rl(op: asmcodes; reg1: registers; symno: cardinal); external;
procedure emit_rll(op: asmcodes; reg1: registers; labelno: cardinal); external;
procedure emit_l(op: asmcodes; symno: cardinal); external;
procedure emit_ll(op: asmcodes; labelno: cardinal); external;
procedure emit_ril(op: asmcodes; reg1: registers; immediate: integer; symno: cardinal); external;
procedure emit_rill(op: asmcodes; reg1: registers; immediate: integer; labelno: cardinal); external;
procedure define_label(labelno: cardinal); external;
procedure emit_itext(var value: Valu); external;
procedure demit_itext(var value: Valu); external;
procedure emit_dir0(instr: itype; arg1: integer); external;
procedure emit_dir1(instr: itype; symno: cardinal; arg2: integer); external;
procedure emit_dir2(instr: itype; symno: cardinal; arg2: integer; arg3: integer); external;
procedure emit_alias(instr: itype; reg1: registers; reg2: registers); external;
procedure emit_regmask(instr: itype; regmask: integer; regoffset: integer); external;
procedure emit_loopno(loopnum: integer; lflag: integer); external;
procedure emit_dir_ll(labelno: cardinal; expression: integer); external;
procedure demit_rob_(op: asmcodes; reg1: registers; immediate: integer; reg2: registers; formextn: format_extn); external;
procedure demit_ri(op: asmcodes; reg1: registers; immediate: integer; formextn: format_extn); external;
procedure demit_rr(op: asmcodes; reg1: registers; reg2: registers); external;
procedure demit_a(op: asmcodes; symno: cardinal; immediate: integer); external;
procedure demit_regmask(instr: itype; regmask: integer; regoffset: integer); external;
procedure demit_rrr(op: asmcodes; reg1: registers; reg2: registers; reg3: registers); external;
procedure demit_rri(op: asmcodes; reg1: registers; reg2: registers; immediate: integer); external;
procedure demit_rrll(op: asmcodes; reg1: registers; reg2: registers; labelno: cardinal); external;
procedure demit_i(op: asmcodes; immediate: integer); external;
procedure demit_ra(op: asmcodes; reg1: registers; symno: integer; immediate: integer); external;
procedure demit_dir0(instr: itype; arg1: integer); external;
procedure demit_dir1(instr: itype; symno: cardinal; arg2: integer); external;
procedure demit_dir2(instr: itype; symno: cardinal; arg2: integer; arg3: integer); external;
procedure demit_edata(symno: cardinal; flag: integer; edata: integer); external;
procedure demit_weakext(symno: cardinal; lexlevel: integer); external;
procedure emit_cpload(reg1: registers; immediate: integer; symno: cardinal; arg3: boolean); external;
procedure ddefine_label(labelno: cardinal); external;
procedure define_exception_label(labelno: cardinal); external;
procedure append_i(var inst: binasm); external;
procedure append_d(var inst: binasm); external;
procedure clear_ibuffer(); external;
procedure emit_vreg(reg1: registers; immediate: integer; symno: cardinal); external;
procedure emit_pic(arg0: integer); external;
procedure demit_cpalias(reg1: registers); external;
procedure emit_cpalias(reg1: registers); external;
procedure emit_cpadd(reg1: registers); external;
#endif /* EMIT_H */
