#include "stdio.h"
#include "stdlib.h"


#ifdef GLOBAL_ASM_FILE
GLOBAL_ASM(
.section .rodata
/*.late_rodata_alignment 4*/
glabel jtbl_1000CE5C
/* 09CE5C 1000CE5C F03F1EE0 */ .gpword .L0041CC90
/* 09CE60 1000CE60 F03F1ED8 */ .gpword .L0041CC88
/* 09CE64 1000CE64 F03F1ED8 */ .gpword .L0041CC88
/* 09CE68 1000CE68 F03F1ED8 */ .gpword .L0041CC88
/* 09CE6C 1000CE6C F03F1ED8 */ .gpword .L0041CC88
/* 09CE70 1000CE70 F03F1ED8 */ .gpword .L0041CC88
/* 09CE74 1000CE74 F03F1ED8 */ .gpword .L0041CC88
/* 09CE78 1000CE78 F03F1ED8 */ .gpword .L0041CC88
/* 09CE7C 1000CE7C F03F1F1C */ .gpword .L0041CCCC
/* 09CE80 1000CE80 F03F1F1C */ .gpword .L0041CCCC
/* 09CE84 1000CE84 F03F1F1C */ .gpword .L0041CCCC
/* 09CE88 1000CE88 F03F1F1C */ .gpword .L0041CCCC
/* 09CE8C 1000CE8C F03F1F1C */ .gpword .L0041CCCC
/* 09CE90 1000CE90 F03F1F1C */ .gpword .L0041CCCC
/* 09CE94 1000CE94 F03F1F1C */ .gpword .L0041CCCC
/* 09CE98 1000CE98 F03F1F1C */ .gpword .L0041CCCC
/* 09CE9C 1000CE9C F03F1F1C */ .gpword .L0041CCCC
/* 09CEA0 1000CEA0 F03F1F00 */ .gpword .L0041CCB0
/* 09CEA4 1000CEA4 F03F1F1C */ .gpword .L0041CCCC
/* 09CEA8 1000CEA8 F03F1F1C */ .gpword .L0041CCCC
/* 09CEAC 1000CEAC F03F1ED8 */ .gpword .L0041CC88
/* 09CEB0 1000CEB0 F03F1ED8 */ .gpword .L0041CC88
/* 09CEB4 1000CEB4 F03F1ED8 */ .gpword .L0041CC88
/* 09CEB8 1000CEB8 F03F1ED8 */ .gpword .L0041CC88


.section .text
/* Generated by spimdisasm 1.12.4 */

glabel func_0041CC50 # 108
/* 01CC50 0041CC50 3C1C0FC1 */  lui         $gp, %hi(_gp_disp)
/* 01CC54 0041CC54 279CE160 */  addiu       $gp, $gp, %lo(_gp_disp)
# _gp_disp: 0xFC0E160
/* 01CC58 0041CC58 0399E021 */  addu        $gp, $gp, $t9
/* 01CC5C 0041CC5C 00047682 */  srl         $t6, $a0, 26
/* 01CC60 0041CC60 2DC10018 */  sltiu       $at, $t6, 0x18
/* 01CC64 0041CC64 10200019 */  beqz        $at, .L0041CCCC
/* 01CC68 0041CC68 AFA40000 */   sw         $a0, 0x0($sp)
/* 01CC6C 0041CC6C 8F818044 */  lw          $at, %got(jtbl_1000CE5C)($gp)
/* 01CC70 0041CC70 000E7080 */  sll         $t6, $t6, 2
/* 01CC74 0041CC74 002E0821 */  addu        $at, $at, $t6
/* 01CC78 0041CC78 8C2ECE5C */  lw          $t6, %lo(jtbl_1000CE5C)($at)
/* 01CC7C 0041CC7C 01DC7021 */  addu        $t6, $t6, $gp
/* 01CC80 0041CC80 01C00008 */  jr          $t6
/* 01CC84 0041CC84 00000000 */   nop
.L0041CC88:
/* 01CC88 0041CC88 03E00008 */  jr          $ra
/* 01CC8C 0041CC8C 24020001 */   addiu      $v0, $zero, 0x1
.L0041CC90:
/* 01CC90 0041CC90 3082003F */  andi        $v0, $a0, 0x3F
/* 01CC94 0041CC94 24010008 */  addiu       $at, $zero, 0x8
/* 01CC98 0041CC98 10410003 */  beq         $v0, $at, .L0041CCA8
/* 01CC9C 0041CC9C 24010009 */   addiu      $at, $zero, 0x9
/* 01CCA0 0041CCA0 5441000B */  bnel        $v0, $at, .L0041CCD0
/* 01CCA4 0041CCA4 00001025 */   move       $v0, $zero
.L0041CCA8:
/* 01CCA8 0041CCA8 03E00008 */  jr          $ra
/* 01CCAC 0041CCAC 24020001 */   addiu      $v0, $zero, 0x1
.L0041CCB0:
/* 01CCB0 0041CCB0 00047980 */  sll         $t7, $a0, 6
/* 01CCB4 0041CCB4 000FC6C2 */  srl         $t8, $t7, 27
/* 01CCB8 0041CCB8 24010008 */  addiu       $at, $zero, 0x8
/* 01CCBC 0041CCBC 57010004 */  bnel        $t8, $at, .L0041CCD0
/* 01CCC0 0041CCC0 00001025 */   move       $v0, $zero
/* 01CCC4 0041CCC4 03E00008 */  jr          $ra
/* 01CCC8 0041CCC8 24020001 */   addiu      $v0, $zero, 0x1
.L0041CCCC:
/* 01CCCC 0041CCCC 00001025 */  move        $v0, $zero
.L0041CCD0:
/* 01CCD0 0041CCD0 03E00008 */  jr          $ra
/* 01CCD4 0041CCD4 00000000 */   nop
)
#endif

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041CCE0.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041CD20.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041CD7C.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/dump_bb.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041CF60.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041CFD0.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041D588.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041D6F4.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041D7D8.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041DAE0.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/create_label_pinst.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041DC04.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041DE5C.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041E0FC.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041E2B4.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041E3B0.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041E544.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041E5C4.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/find_branch_target.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041E748.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041EEA4.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/create_prolog_and_epilog_bbs.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041F8A4.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041F938.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/init_j_def_live.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041FAA4.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041FE50.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_0041FF80.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_00420194.s")

#ifdef GLOBAL_ASM_FILE
GLOBAL_ASM(
.section .rodata
/*.late_rodata_alignment 8*/
glabel jtbl_1000D028
/* 09D028 1000D028 F03F5508 */ .gpword .L004202B8
/* 09D02C 1000D02C F03F5508 */ .gpword .L004202B8
/* 09D030 1000D030 F03F5514 */ .gpword .L004202C4
/* 09D034 1000D034 F03F5514 */ .gpword .L004202C4
/* 09D038 1000D038 F03F5514 */ .gpword .L004202C4
/* 09D03C 1000D03C F03F5514 */ .gpword .L004202C4
/* 09D040 1000D040 F03F5508 */ .gpword .L004202B8
/* 09D044 1000D044 F03F5508 */ .gpword .L004202B8
/* 09D048 1000D048 F03F5508 */ .gpword .L004202B8
/* 09D04C 1000D04C F03F5508 */ .gpword .L004202B8
/* 09D050 1000D050 F03F5508 */ .gpword .L004202B8
/* 09D054 1000D054 F03F5508 */ .gpword .L004202B8
/* 09D058 1000D058 F03F5508 */ .gpword .L004202B8
/* 09D05C 1000D05C F03F5514 */ .gpword .L004202C4
/* 09D060 1000D060 F03F5514 */ .gpword .L004202C4
/* 09D064 1000D064 F03F5514 */ .gpword .L004202C4
/* 09D068 1000D068 F03F5514 */ .gpword .L004202C4
/* 09D06C 1000D06C F03F5514 */ .gpword .L004202C4
/* 09D070 1000D070 F03F5514 */ .gpword .L004202C4
/* 09D074 1000D074 F03F5514 */ .gpword .L004202C4
/* 09D078 1000D078 F03F5514 */ .gpword .L004202C4
/* 09D07C 1000D07C F03F5514 */ .gpword .L004202C4
/* 09D080 1000D080 F03F5508 */ .gpword .L004202B8
/* 09D084 1000D084 F03F5514 */ .gpword .L004202C4
/* 09D088 1000D088 F03F5514 */ .gpword .L004202C4
/* 09D08C 1000D08C F03F5514 */ .gpword .L004202C4
/* 09D090 1000D090 F03F5508 */ .gpword .L004202B8
/* 09D094 1000D094 F03F5514 */ .gpword .L004202C4
/* 09D098 1000D098 F03F5514 */ .gpword .L004202C4
/* 09D09C 1000D09C F03F5508 */ .gpword .L004202B8


.section .text
/* Generated by spimdisasm 1.12.4 */

glabel func_0042027C # 140
/* 02027C 0042027C 3C1C0FC1 */  lui         $gp, %hi(_gp_disp)
/* 020280 00420280 279CAB34 */  addiu       $gp, $gp, %lo(_gp_disp)
# _gp_disp: 0xFC0AB34
/* 020284 00420284 0399E021 */  addu        $gp, $gp, $t9
/* 020288 00420288 00047E82 */  srl         $t7, $a0, 26
/* 02028C 0042028C 25F8FFE6 */  addiu       $t8, $t7, -0x1A
/* 020290 00420290 2F01001E */  sltiu       $at, $t8, 0x1E
/* 020294 00420294 1020000B */  beqz        $at, .L004202C4
/* 020298 00420298 AFA40000 */   sw         $a0, 0x0($sp)
/* 02029C 0042029C 8F818044 */  lw          $at, %got(jtbl_1000D028)($gp)
/* 0202A0 004202A0 0018C080 */  sll         $t8, $t8, 2
/* 0202A4 004202A4 00380821 */  addu        $at, $at, $t8
/* 0202A8 004202A8 8C38D028 */  lw          $t8, %lo(jtbl_1000D028)($at)
/* 0202AC 004202AC 031CC021 */  addu        $t8, $t8, $gp
/* 0202B0 004202B0 03000008 */  jr          $t8
/* 0202B4 004202B4 00000000 */   nop
.L004202B8:
/* 0202B8 004202B8 97A20000 */  lhu         $v0, 0x0($sp)
/* 0202BC 004202BC 03E00008 */  jr          $ra
/* 0202C0 004202C0 3042001F */   andi       $v0, $v0, 0x1F
.L004202C4:
/* 0202C4 004202C4 00001025 */  move        $v0, $zero
/* 0202C8 004202C8 03E00008 */  jr          $ra
/* 0202CC 004202CC 00000000 */   nop
)
#endif

#pragma GLOBAL_ASM("asm/7.1/functions/as1/appendtextword.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_004206BC.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/traverse_bb.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/init_inst_heap.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/backup_pinst.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_00421DAC.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/func_00421EBC.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/initbb.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/pseudo_type.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/fill_pseudo.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/fill_ascii_pseudo.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/fill_inst.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/update_regs_in_inst.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/fixup_preceding_labels.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/flip_bits.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/flush_line_no.s")

#pragma GLOBAL_ASM("asm/7.1/functions/as1/ll_load_immed.s")

