#include "cmplrs/usys.h"
#include "cmplrs/ucode.h"

var 
	Utab: array[first(Uopcode)..last(Uopcode)] of Utabrec;


procedure Uini;
var
    pos: integer;
    op: Uopcode;

    
    procedure opc(opcode: Uopcode; Opcname: Opcstring); internal;
    begin
        Utab[opcode].Opcname := Opcname; \
        op := opcode; \
        pos := 0; \
    end;
    
    procedure push(operand: Uoperand); internal;
    begin
        pos := pos + 1;
        Utab[op].Format[pos] := operand;
    end;
begin

    (* Opcode *)               (* Pushes *)
    opc(Uabs,  "ABS "); push(Sdtype); push(Send);
    opc(Uadd,  "ADD "); push(Sdtype); push(Send);
    opc(Uadj,  "ADJ "); push(Sdtype); push(Soffset); push(Slength); push(Send);
    opc(Ualia, "ALIA"); push(Ssomenumber); push(Slexlev); push(Send);
    opc(Uand,  "AND "); push(Sdtype); push(Send);
    opc(Uaos,  "AOS "); push(Send);
    opc(Ubgn,  "BGN "); push(Sblockno); push(Slength); push(Soffset); push(Send);
    opc(Ubgnb, "BGNB"); push(Sblockno); push(Send);
    opc(Ubsub, "BSUB"); push(Sdtype); push(Send);
    opc(Uchkt, "CHKT"); push(Send);
    opc(Uchkh, "CHKH"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Uchkl, "CHKL"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Uchkn, "CHKN"); push(Send);
    opc(Ucia,  "CIA "); push(Sdtype); push(Slength); push(Slexlev); push(Soffset); push(Ssomenumber); push(Sconstval); push(Send);
    opc(Uclab, "CLAB"); push(Slabel0); push(Slength); push(Send);
    opc(Uclbd, "CLBD"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Ucubd, "CUBD"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Uctrl, "CTRL"); push(Sdtype); push(Smtype); push(Sblockno);  push(Soffset); push(Slength); push(Send);
    opc(Ucomm, "COMM"); push(Scomment); push(Send);
    opc(Ucup,  "CUP "); push(Sdtype); push(Slexlev); push(Sblockno); push(Spop); push(Spush); push(Sexternal); push(Send);
    opc(Ucvt,  "CVT "); push(Sdtype); push(Sdtype2); push(Send);
    opc(Ucvtl, "CVTL"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Udec,  "DEC "); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Udef,  "DEF "); push(Smtype); push(Slength); push(Send);
    opc(Udif,  "DIF "); push(Sdtype); push(Slength); push(Send);
    opc(Udiv,  "DIV "); push(Sdtype); push(Send);
    opc(Udup,  "DUP "); push(Sdtype); push(Send);
    opc(Uend,  "END "); push(Sblockno); push(Send);
    opc(Uendb, "ENDB"); push(Sblockno); push(Send);
    opc(Uent,  "ENT "); push(Sdtype); push(Slexlev); push(Sblockno); push(Spop); push(Spush); push(Sexternal); push(Send);
    opc(Uaent, "AENT"); push(Sdtype); push(Slexlev); push(Sblockno); push(Spop); push(Spush); push(Sexternal); push(Send);
    opc(Uequ,  "EQU "); push(Sdtype); push(Send);
    opc(Ufjp,  "FJP "); push(Slabel1); push(Slexlev); push(Send);
    opc(Ugeq,  "GEQ "); push(Sdtype); push(Send);
    opc(Ugrt,  "GRT "); push(Sdtype); push(Send);
    opc(Ufill, "FILL"); push(Sdtype); push(Ssomenumber); push(Slength); push(Send);
    opc(Uidx,  "IDX "); push(Sdtype); push(Send);
    opc(Uiequ, "IEQU"); push(Sdtype); push(Ssomenumber); push(Slength); push(Send);
    opc(Uigeq, "IGEQ"); push(Sdtype); push(Ssomenumber); push(Slength); push(Send);
    opc(Uigrt, "IGRT"); push(Sdtype); push(Ssomenumber); push(Slength); push(Send);
    opc(Uileq, "ILEQ"); push(Sdtype); push(Ssomenumber); push(Slength); push(Send);
    opc(Uiles, "ILES"); push(Sdtype); push(Ssomenumber); push(Slength); push(Send);
    opc(Uilod, "ILOD"); push(Sdtype); push(Ssomenumber); push(Slexlev); push(Slength); push(Soffset); push(Send);
    opc(Uineq, "INEQ"); push(Sdtype); push(Slength); push(Send);
    opc(Uinc,  "INC "); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Uinit, "INIT"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Soffset2); push(Slength); push(SarrayOffset); push(Slexlev); push(Sinitval); push(Send);
    opc(Uinn,  "INN "); push(Sdtype); push(Slength); push(Ssomenumber); push(Send);
    opc(Uint,  "INT "); push(Sdtype); push(Slength); push(Send);
    opc(Uior,  "IOR "); push(Sdtype); push(Send);
    opc(Uistr, "ISTR"); push(Sdtype); push(Ssomenumber); push(Slexlev); push(Slength); push(Soffset); push(Send);
    opc(Uixa,  "IXA "); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Ulab,  "LAB "); push(Slabel0); push(Slexlev); push(Slength); push(Send);
    opc(Uldef, "LDEF"); push(Slabel0); push(Slexlev); push(Slength); push(Send);
    opc(Ulbd,  "LBD "); push(Send);
    opc(Ulca,  "LCA "); push(Sdtype); push(Slength); push(Ssomenumber); push(Sconstval); push(Send);
    opc(Uilda, "ILDA"); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Soffset2); push(Send);
    opc(Ulda,  "LDA "); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Soffset2); push(Send);
    opc(Uldc,  "LDC "); push(Sdtype); push(Slength); push(Sconstval); push(Send);
    opc(Uldsp, "LDSP"); push(Send);
    opc(Uldap, "LDAP"); push(Send);
    opc(Uleq,  "LEQ "); push(Sdtype); push(Send);
    opc(Ules,  "LES "); push(Sdtype); push(Send);
    opc(Ulex,  "LEX "); push(Slexlev); push(Sblockno); push(Send);
    opc(Uloc,  "LOC "); push(Slexlev); push(Ssomenumber); push(Send);
    opc(Ulod,  "LAD "); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Send);
    opc(Umin,  "MIN "); push(Sdtype); push(Send);
    opc(Umax,  "MAX "); push(Sdtype); push(Send);
    opc(Umod,  "MOD "); push(Sdtype); push(Send);
    opc(Urem,  "REM "); push(Sdtype); push(Send);
    opc(Umov,  "MOV "); push(Sdtype); push(Slexlev); push(Ssomenumber); push(Slength); push(Send);
    opc(Umpy,  "MPY "); push(Sdtype); push(Send);
    opc(Umst,  "MST "); push(Slexlev); push(Send);
    opc(Umtag, "MTAG"); push(Ssomenumber); push(Slexlev); push(Send);
    opc(Umus,  "MUS "); push(Sdtype); push(Slength); push(Send);
    opc(Uneg,  "NEG "); push(Sdtype); push(Send);
    opc(Uneq,  "NEQ "); push(Sdtype); push(Send);
    opc(Unop,  "NOP "); push(Send);
    opc(Unot,  "NOT "); push(Sdtype); push(Send);
    opc(Uodd,  "ODD "); push(Sdtype); push(Send);
    opc(Uxpar, "XPAR"); push(Sdtype); push(Send);
    opc(Uoptn, "OPTN"); push(Ssomenumber); push(Slength); push(Send);
    opc(Upar,  "PAR "); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Send);
    opc(Updef, "PDEF"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Upop,  "POP "); push(Sdtype); push(Send);
    opc(Uregs, "REGS"); push(Slexlev); push(Ssomenumber); push(Soffset); push(Slength); push(Send);
    opc(Uret,  "RET "); push(Send);
    opc(Urlda, "RLDA"); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Send);
    opc(Urldc, "RLDC"); push(Sdtype); push(Slength); push(Ssomenumber); push(Sconstval); push(Send);
    opc(Urlod, "RLOD"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Urnd,  "RND "); push(Sdtype); push(Sdtype2); push(Send);
    opc(Urpar, "RPAR"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Urstr, "RSTR"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Usdef, "SDEF"); push(Sblockno); push(Slength); push(Send);
    opc(Uasym, "ASYM"); push(Sblockno); push(Slength); push(Slexlev); push(Send);
    opc(Uhsym, "HSYM"); push(Sblockno); push(Slength); push(Send);
    opc(Usgs,  "SGS "); push(Sdtype); push(Slength); push(Send);
    opc(Usqr,  "SQR "); push(Sdtype); push(Send);
    opc(Usqrt, "SQRT"); push(Sdtype); push(Send);
    opc(Ustep, "STEP"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Ustp,  "STP "); push(Sblockno); push(Send);
    opc(Ustr,  "STR "); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Send);
    opc(Ustsp, "STSP"); push(Send);
    opc(Usub,  "SUB "); push(Sdtype); push(Send);
    opc(Uswp,  "SWP "); push(Sdtype); push(Sdtype2); push(Send);
    opc(Utjp,  "TJP "); push(Slabel1); push(Slexlev); push(Send);
    opc(Utyp,  "TYP "); push(Sdtype); push(Sdtype2); push(Send);
    opc(Uujp,  "UJP "); push(Slabel1); push(Send);
    opc(Uuni,  "UNI "); push(Sdtype); push(Slength); push(Send);
    opc(Uxjp,  "XJP "); push(Sdtype); push(Slabel1); push(Slabel2); push(Slbound); push(Shbound); push(Send);
    opc(Uxor,  "XOR "); push(Sdtype); push(Send);
    opc(Ucsym, "CSYM"); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Uesym, "ESYM"); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Ufsym, "FSYM"); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Ugsym, "GSYM"); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Ulsym, "LSYM"); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Ushl,  "SHL "); push(Sdtype); push(Send);
    opc(Ushr,  "SHR "); push(Sdtype); push(Send);
    opc(Ulnot, "LNOT"); push(Sdtype); push(Send);
    opc(Uicuf, "ICUF"); push(Sdtype); push(Spop); push(Spush); push(Sexternal); push(Send);
    opc(Uisld, "ISLD"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Uisst, "ISST"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Upmov, "PMOV"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Umpmv, "MPMV"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Uunal, "UNAL"); push(Slexlev); push(Ssomenumber); push(Sdtypenum); push(Send);
    opc(Uvreg, "VREG"); push(Sdtype); push(Smtype); push(Sblockno); push(Soffset); push(Slength); push(Slexlev); push(Send);
    opc(Uijp,  "IJP "); push(Send);
    opc(Ucg1,  "CG1 "); push(Send);
    opc(Ucg2,  "CG2 "); push(Send);
    opc(Utpeq, "TPEQ"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Utpne, "TPNE"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Utplt, "TPLT"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Utpgt, "TPGT"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Utpge, "TPGE"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Utple, "TPLE"); push(Sdtype); push(Ssomenumber); push(Send);
    opc(Uubd,  "UDB "); push(Send);
    opc(Ulbgn, "LBGN"); push(Ssomenumber); push(Send);
    opc(Ulbdy, "LBDY"); push(Slexlev); push(Send);
    opc(Ultrm, "LTRM"); push(Send);
    opc(Ulend, "LEND"); push(Send);
    opc(Ussym, "SSYM"); push(Sdtype); push(Sblockno); push(Slexlev); push(Sconstval); push(Send);
    opc(Usign, "SIGN"); push(Sdtype); push(Send);
    opc(Uildi, "ILDI"); push(Sdtype); push(Slexlev); push(Slength); push(Soffset); push(Send);
    opc(Uisti, "ISTI"); push(Sdtype); push(Slexlev); push(Slength); push(Soffset); push(Send);
    opc(Uirld, "IRLD"); push(Sdtype); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Uirst, "IRST"); push(Sdtype); push(Sblockno); push(Slexlev); push(Slength); push(Send);
    opc(Uldrc, "LDRC"); push(Sdtype); push(Slength); push(Sblockno); push(Send);
    opc(Urcuf, "RCUF"); push(Sdtype); push(Sblockno); push(Spop); push(Spush); push(Sexternal); push(Send);
    opc(Umsym, "MSYM"); push(Sblockno); push(Soffset); push(Slexlev); push(Slength); push(Send);
    opc(Uksym, "KSYM"); push(Sblockno); push(Soffset); push(Slexlev); push(Slength); push(Send);
    opc(Uosym, "OSYM"); push(Sblockno); push(Soffset); push(Send);



    for op := first(Uopcode) to last(Uopcode) do begin
        Utab[op].Hasattr := false;
        Utab[op].Hasconst := false;
        Utab[op].Instlength := 2;
        Utab[op].Stack_pop := 0;
        Utab[op].Stack_push := 0;
    end;

    Utab[Ulod].Hasattr := true;
    Utab[Ustr].Hasattr := true;
    Utab[Uilod].Hasattr := true;
    Utab[Uistr].Hasattr := true;
    Utab[Uildi].Hasattr := true;
    Utab[Uisti].Hasattr := true;
    Utab[Uirld].Hasattr := true;
    Utab[Uirst].Hasattr := true;
    Utab[Umov].Hasattr := true;
    Utab[Uabs].Hasattr := true;
    Utab[Uneg].Hasattr := true;
    Utab[Usqr].Hasattr := true;
    Utab[Uchkn].Hasattr := true;
    Utab[Uchkt].Hasattr := true;
    Utab[Ulnot].Hasattr := true;
    Utab[Unot].Hasattr := true;
    Utab[Uodd].Hasattr := true;
    Utab[Usqrt].Hasattr := true;
    Utab[Ucvtl].Hasattr := true;
    Utab[Udec].Hasattr := true;
    Utab[Uinc].Hasattr := true;
    Utab[Uchkh].Hasattr := true;
    Utab[Uchkl].Hasattr := true;
    Utab[Usgs].Hasattr := true;
    Utab[Ucvt].Hasattr := true;
    Utab[Urnd].Hasattr := true;
    Utab[Uadj].Hasattr := true;
    Utab[Uadd].Hasattr := true;
    Utab[Udiv].Hasattr := true;
    Utab[Umod].Hasattr := true;
    Utab[Umpy].Hasattr := true;
    Utab[Usub].Hasattr := true;
    Utab[Urem].Hasattr := true;
    Utab[Uand].Hasattr := true;
    Utab[Uequ].Hasattr := true;
    Utab[Ugeq].Hasattr := true;
    Utab[Ugrt].Hasattr := true;
    Utab[Uior].Hasattr := true;
    Utab[Uleq].Hasattr := true;
    Utab[Ules].Hasattr := true;
    Utab[Umax].Hasattr := true;
    Utab[Umin].Hasattr := true;
    Utab[Uneq].Hasattr := true;
    Utab[Ushl].Hasattr := true;
    Utab[Ushr].Hasattr := true;
    Utab[Uxor].Hasattr := true;
    Utab[Uixa].Hasattr := true;
    Utab[Uint].Hasattr := true;
    Utab[Udif].Hasattr := true;
    Utab[Umus].Hasattr := true;
    Utab[Uuni].Hasattr := true;
    Utab[Uinn].Hasattr := true;
    Utab[Uiequ].Hasattr := true;
    Utab[Uigrt].Hasattr := true;
    Utab[Uigeq].Hasattr := true;
    Utab[Uileq].Hasattr := true;
    Utab[Uiles].Hasattr := true;
    Utab[Uineq].Hasattr := true;
    Utab[Usign].Hasattr := true;
    Utab[Uisld].Hasattr := true;
    Utab[Uisst].Hasattr := true;

    Utab[Ucia].Hasconst := true;
    Utab[Ucomm].Hasconst := true;
    Utab[Uinit].Hasconst := true;
    Utab[Ulca].Hasconst := true;
    Utab[Uldc].Hasconst := true;
    Utab[Urldc].Hasconst := true;
    Utab[Ussym].Hasconst := true;

    Utab[Uadj].Instlength := 4;
    Utab[Ubgn].Instlength := 4;
    Utab[Ubgnb].Instlength := 2;
    Utab[Uchkh].Instlength := 2;
    Utab[Uchkl].Instlength := 2;
    Utab[Ucia].Instlength := 4;
    Utab[Uclab].Instlength := 4;
    Utab[Uclbd].Instlength := 2;
    Utab[Ucubd].Instlength := 2;
    Utab[Uctrl].Instlength := 4;
    Utab[Ucomm].Instlength := 4;
    Utab[Ucup].Instlength := 4;
    Utab[Ucvt].Instlength := 4;
    Utab[Ucvtl].Instlength := 2;
    Utab[Udec].Instlength := 2;
    Utab[Uinc].Instlength := 2;
    Utab[Udef].Instlength := 4;
    Utab[Udif].Instlength := 4;
    Utab[Uint].Instlength := 4;
    Utab[Uuni].Instlength := 4;
    Utab[Uend].Instlength := 2;
    Utab[Uendb].Instlength := 2;
    Utab[Uent].Instlength := 4;
    Utab[Uaent].Instlength := 4;
    Utab[Uiequ].Instlength := 4;
    Utab[Uigeq].Instlength := 4;
    Utab[Uigrt].Instlength := 4;
    Utab[Uileq].Instlength := 4;
    Utab[Uiles].Instlength := 4;
    Utab[Uineq].Instlength := 4;
    Utab[Ufjp].Instlength := 2;
    Utab[Utjp].Instlength := 2;
    Utab[Uujp].Instlength := 2;
    Utab[Ufill].Instlength := 4;
    Utab[Uildv].Instlength := 4;
    Utab[Uilod].Instlength := 4;
    Utab[Uinit].Instlength := 6;
    Utab[Uinn].Instlength := 4;
    Utab[Uistv].Instlength := 4;
    Utab[Uistr].Instlength := 4;
    Utab[Uixa].Instlength := 2;
    Utab[Ulab].Instlength := 4;
    Utab[Uldef].Instlength := 4;
    Utab[Ulca].Instlength := 4;
    Utab[Uilda].Instlength := 6;
    Utab[Ulbgn].Instlength := 2;
    Utab[Ulda].Instlength := 6;
    Utab[Uldc].Instlength := 4;
    Utab[Ulex].Instlength := 2;
    Utab[Uloc].Instlength := 2;
    Utab[Ulod].Instlength := 4;
    Utab[Umov].Instlength := 4;
    Utab[Umus].Instlength := 4;
    Utab[Uoptn].Instlength := 4;
    Utab[Upar].Instlength := 4;
    Utab[Updef].Instlength := 4;
    Utab[Uregs].Instlength := 4;
    Utab[Urlda].Instlength := 4;
    Utab[Urldc].Instlength := 4;
    Utab[Urlod].Instlength := 4;
    Utab[Urnd].Instlength := 4;
    Utab[Urpar].Instlength := 4;
    Utab[Urstr].Instlength := 4;
    Utab[Usdef].Instlength := 4;
    Utab[Uasym].Instlength := 4;
    Utab[Uhsym].Instlength := 4;
    Utab[Usgs].Instlength := 4;
    Utab[Ustep].Instlength := 2;
    Utab[Ustp].Instlength := 2;
    Utab[Ustr].Instlength := 4;
    Utab[Uswp].Instlength := 4;
    Utab[Uxjp].Instlength := 8;
    Utab[Ucsym].Instlength := 4;
    Utab[Uesym].Instlength := 4;
    Utab[Ufsym].Instlength := 4;
    Utab[Ugsym].Instlength := 4;
    Utab[Ulsym].Instlength := 4;
    Utab[Uicuf].Instlength := 4;
    Utab[Uisld].Instlength := 4;
    Utab[Uisst].Instlength := 4;
    Utab[Upmov].Instlength := 4;
    Utab[Umpmv].Instlength := 4;
    Utab[Uunal].Instlength := 2;
    Utab[Uvreg].Instlength := 4;
    Utab[Utpeq].Instlength := 2;
    Utab[Utpne].Instlength := 2;
    Utab[Utplt].Instlength := 2;
    Utab[Utpgt].Instlength := 2;
    Utab[Utpge].Instlength := 2;
    Utab[Utple].Instlength := 2;
    Utab[Utyp].Instlength := 4;
    Utab[Ussym].Instlength := 4;
    Utab[Urcuf].Instlength := 4;
    Utab[Uldrc].Instlength := 4;
    Utab[Umsym].Instlength := 4;
    Utab[Uksym].Instlength := 4;
    Utab[Uosym].Instlength := 4;
    Utab[Uildi].Instlength := 4;
    Utab[Uisti].Instlength := 4;
    Utab[Uirld].Instlength := 4;
    Utab[Uirst].Instlength := 4;

    Utab[Ustr].Stack_pop := 1;
    Utab[Uchkn].Stack_pop := 1;
    Utab[Uchkt].Stack_pop := 1;
    Utab[Uabs].Stack_pop := 1;
    Utab[Ubsub].Stack_pop := 2;
    Utab[Uneg].Stack_pop := 1;
    Utab[Usqr].Stack_pop := 1;
    Utab[Ulnot].Stack_pop := 1;
    Utab[Unot].Stack_pop := 1;
    Utab[Uodd].Stack_pop := 1;
    Utab[Usqrt].Stack_pop := 1;
    Utab[Ucvtl].Stack_pop := 1;
    Utab[Udec].Stack_pop := 1;
    Utab[Uinc].Stack_pop := 1;
    Utab[Uchkh].Stack_pop := 1;
    Utab[Uchkl].Stack_pop := 1;
    Utab[Usgs].Stack_pop := 1;
    Utab[Ucvt].Stack_pop := 1;
    Utab[Utyp].Stack_pop := 1;
    Utab[Urnd].Stack_pop := 1;
    Utab[Uadj].Stack_pop := 1;
    Utab[Uilda].Stack_pop := 1;
    Utab[Ulbd].Stack_pop := 1;
    Utab[Uubd].Stack_pop := 1;
    Utab[Uadd].Stack_pop := 2;
    Utab[Udiv].Stack_pop := 2;
    Utab[Umod].Stack_pop := 2;
    Utab[Umpy].Stack_pop := 2;
    Utab[Usub].Stack_pop := 2;
    Utab[Urem].Stack_pop := 2;
    Utab[Uand].Stack_pop := 2;
    Utab[Uequ].Stack_pop := 2;
    Utab[Ugeq].Stack_pop := 2;
    Utab[Ugrt].Stack_pop := 2;
    Utab[Uior].Stack_pop := 2;
    Utab[Uleq].Stack_pop := 2;
    Utab[Ules].Stack_pop := 2;
    Utab[Umax].Stack_pop := 2;
    Utab[Umin].Stack_pop := 2;
    Utab[Uneq].Stack_pop := 2;
    Utab[Ushl].Stack_pop := 2;
    Utab[Ushr].Stack_pop := 2;
    Utab[Uxor].Stack_pop := 2;
    Utab[Uixa].Stack_pop := 2;
    Utab[Uidx].Stack_pop := 3;
    Utab[Uint].Stack_pop := 2;
    Utab[Udif].Stack_pop := 2;
    Utab[Umus].Stack_pop := 2;
    Utab[Uuni].Stack_pop := 2;
    Utab[Uinn].Stack_pop := 2;
    Utab[Uilod].Stack_pop := 1;
    Utab[Uistr].Stack_pop := 2;
    Utab[Uildi].Stack_pop := 2;
    Utab[Uisti].Stack_pop := 3;
    Utab[Uirld].Stack_pop := 1;
    Utab[Uirst].Stack_pop := 2;
    Utab[Uisld].Stack_pop := 1;
    Utab[Uisst].Stack_pop := 2;
    Utab[Umov].Stack_pop := 2;
    Utab[Ufill].Stack_pop := 2;
    Utab[Uiequ].Stack_pop := 2;
    Utab[Uigeq].Stack_pop := 2;
    Utab[Uigrt].Stack_pop := 2;
    Utab[Uileq].Stack_pop := 2;
    Utab[Uiles].Stack_pop := 2;
    Utab[Uineq].Stack_pop := 2;
    Utab[Ufjp].Stack_pop := 1;
    Utab[Utjp].Stack_pop := 1;
    Utab[Uijp].Stack_pop := 1;
    Utab[Uxjp].Stack_pop := 1;
    Utab[Uicuf].Stack_pop := 1;
    Utab[Upar].Stack_pop := 1;
    Utab[Uxpar].Stack_pop := 1;
    Utab[Upmov].Stack_pop := 1;
    Utab[Umpmv].Stack_pop := 1;
    Utab[Utpeq].Stack_pop := 2;
    Utab[Utpge].Stack_pop := 2;
    Utab[Utpgt].Stack_pop := 2;
    Utab[Utple].Stack_pop := 2;
    Utab[Utplt].Stack_pop := 2;
    Utab[Utpne].Stack_pop := 2;
    Utab[Upop].Stack_pop := 1;
    Utab[Uswp].Stack_pop := 1;
    Utab[Uaos].Stack_pop := 1;
    Utab[Ustsp].Stack_pop := 1;
    Utab[Usign].Stack_pop := 2;

    Utab[Ulod].Stack_push := 1;
    Utab[Uldc].Stack_push := 1;
    Utab[Uldrc].Stack_push := 1;
    Utab[Ulca].Stack_push := 1;
    Utab[Ulda].Stack_push := 1;
    Utab[Uchkn].Stack_push := 1;
    Utab[Uabs].Stack_push := 1;
    Utab[Ubsub].Stack_push := 1;
    Utab[Uneg].Stack_push := 1;
    Utab[Usqr].Stack_push := 1;
    Utab[Ulnot].Stack_push := 1;
    Utab[Unot].Stack_push := 1;
    Utab[Uodd].Stack_push := 1;
    Utab[Usqrt].Stack_push := 1;
    Utab[Ucvtl].Stack_push := 1;
    Utab[Udec].Stack_push := 1;
    Utab[Uinc].Stack_push := 1;
    Utab[Uchkh].Stack_push := 1;
    Utab[Uchkl].Stack_push := 1;
    Utab[Usgs].Stack_push := 1;
    Utab[Ucvt].Stack_push := 1;
    Utab[Utyp].Stack_push := 1;
    Utab[Urnd].Stack_push := 1;
    Utab[Uadj].Stack_push := 1;
    Utab[Uilda].Stack_push := 1;
    Utab[Ulbd].Stack_push := 1;
    Utab[Uubd].Stack_push := 1;
    Utab[Uadd].Stack_push := 1;
    Utab[Udiv].Stack_push := 1;
    Utab[Umod].Stack_push := 1;
    Utab[Umpy].Stack_push := 1;
    Utab[Usub].Stack_push := 1;
    Utab[Urem].Stack_push := 1;
    Utab[Uand].Stack_push := 1;
    Utab[Uequ].Stack_push := 1;
    Utab[Ugeq].Stack_push := 1;
    Utab[Ugrt].Stack_push := 1;
    Utab[Uior].Stack_push := 1;
    Utab[Uleq].Stack_push := 1;
    Utab[Ules].Stack_push := 1;
    Utab[Umax].Stack_push := 1;
    Utab[Umin].Stack_push := 1;
    Utab[Uneq].Stack_push := 1;
    Utab[Ushl].Stack_push := 1;
    Utab[Ushr].Stack_push := 1;
    Utab[Uxor].Stack_push := 1;
    Utab[Uixa].Stack_push := 1;
    Utab[Uidx].Stack_push := 1;
    Utab[Uint].Stack_push := 1;
    Utab[Udif].Stack_push := 1;
    Utab[Umus].Stack_push := 1;
    Utab[Uuni].Stack_push := 1;
    Utab[Uinn].Stack_push := 1;
    Utab[Uilod].Stack_push := 1;
    Utab[Uildi].Stack_push := 1;
    Utab[Uirld].Stack_push := 1;
    Utab[Uisld].Stack_push := 1;
    Utab[Uiequ].Stack_push := 1;
    Utab[Uigeq].Stack_push := 1;
    Utab[Uigrt].Stack_push := 1;
    Utab[Uileq].Stack_push := 1;
    Utab[Uiles].Stack_push := 1;
    Utab[Uineq].Stack_push := 1;
    Utab[Udup].Stack_push := 1;
    Utab[Uswp].Stack_push := 1;
    Utab[Uldsp].Stack_push := 1;
    Utab[Uldap].Stack_push := 1;
    Utab[Usign].Stack_push := 1;

end;

procedure getutabrec(
	    Uopc     : Uopcode;
	var Utabr    : Utabrec);
begin
    Utabr := Utab[Uopc];
end;
