#ifndef MODES_H
#define MODES_H

#define IS_ANSI ((options[OPTION_CPLUSPLUS] && (options[OPTION_ANSI_MODE] & 1) || !options[OPTION_CPLUSPLUS] && (options[OPTION_ANSI_MODE] & 1)))
#define IS_STRICT_ANSI (IS_ANSI && (options[OPTION_ANSI_MODE] & 5) == 5)
#define IS_RELAXED_ANSI (IS_ANSI && (options[OPTION_ANSI_MODE] & 3) == 3)

enum Option {
    OPTION_O_LEVEL = 0,
    OPTION_G_LEVEL = 1,
    OPTION_ENDIANNESS = 2,
    OPTION_VERBOSITY = 3,
    OPTION_FLOAT = 4,
    OPTION_ANSI_MODE = 5,
    OPTION_SIGNED = 6,
    OPTION_DOLLAR = 7,
    OPTION_T_LEVEL = 8,
    OPTION_FRAMEPOINTER = 9,
    OPTION_TRAPUV = 10,
    OPTION_11 = 11, // unused ?
    OPTION_MIPS_GEN = 12,
    OPTION_CPLUSPLUS = 13,
    OPTION_14 = 14,
    OPTION_CHECKSTACK = 15,
    OPTION_T = 16,
    OPTION_CHECK_BOUNDS = 17,
    OPTION_SAVEARGS = 18,
    OPTION_LINT_FLAGS = 19,
    OPTION_WIMPLICIT = 20,
    OPTION_MSFT = 21,
    OPTION_PROTOTYPES = 22,
    OPTION_FULLWARN = 23,
    OPTION_XCOMMON = 24,
    OPTION_VOLATILE = 25,
    OPTION_CPLUSCOMM = 26,
    OPTION_READONLY_CONST = 27,
    OPTION_LITERAL_CONST = 28,
};

enum VerbosityFlags {
    VERBOSE_FLAG_1 = 0x1,
    VERBOSE_FLAG_2 = 0x2,
    VERBOSE_FLAG_4 = 0x4,
    VERBOSE_FLAG_8 = 0x8,
    VERBOSE_FLAG_10 = 0x10,
    VERBOSE_FLAG_20 = 0x20,
};

void init_options(void);

#endif